const myProducts = [
    {
        id: 1,
        image: "https://reebokarg.vtexassets.com/arquivos/ids/168922-1600-1600?v=638032296357630000&width=1600&height=1600&aspect=true",
        name: 'Nano X2 MEN',
        description: "From pistol squats to burpees, there's no shortage of moves to take your training to the next level.",
        detail: "From pistol squats to burpees, there's no shortage of moves to take your training to the next level.From pistol squats to burpees, there's no shortage of moves to take your training to the next level.",
        price: 150,
        type: 'shoe',
        stock: 12,
    },
    {
        id: 2,
        image: "https://reebokarg.vtexassets.com/arquivos/ids/170741-1600-1600?v=638037488613370000&width=1600&height=1600&aspect=true",
        name: 'Nano X2 WOMEN',
        description: "From pistol squats to burpees, there's no shortage of moves to take your training to the next level.",
        detail: "From pistol squats to burpees, there's no shortage of moves to take your training to the next level.From pistol squats to burpees, there's no shortage of moves to take your training to the next level.",
        price: 150,
        type: 'shoe',
        stock: 12,
    },
    {
        id: 3,
        image: "https://reebokarg.vtexassets.com/arquivos/ids/163510-800-800?v=638005364895500000&width=800&height=800&aspect=true",
        name: 'Nano X1 MEN',
        description: "From pistol squats to burpees, there's no shortage of moves to take your training to the next level.",
        detail: "From pistol squats to burpees, there's no shortage of moves to take your training to the next level.From pistol squats to burpees, there's no shortage of moves to take your training to the next level.",
        price: 150,
        type: 'shoe',
        stock: 12,
    },
    {
        id: 4,
        image: "https://reebokarg.vtexassets.com/arquivos/ids/162054-800-800?v=638005280637370000&width=800&height=800&aspect=true",
        name: 'Classic Linear',
        description: "It may look like a common t-shirt. But this men's garment has much more than you expect. The linear logo design gives it a modern Reebok look.",
        detail: "It may look like a common t-shirt. But this men's garment has much more than you expect. The linear logo design gives it a modern Reebok look. You know that t-shirt you've had for years and love because it's super soft? Well that's how good this feels.",
        price: 150,
        type: 'shirt',
        stock: 12,
    },
    {
        id: 5,
        image: "https://reebokarg.vtexassets.com/arquivos/ids/157857-800-800?v=637988055258800000&width=800&height=800&aspect=true",
        name: 'Calleras Training',
        description: "Maximum grip. These grips maximize the feel when gripping the bar with minimal coverage.",
        detail: "Maximum grip. These grips maximize the feel when gripping the bar with minimal coverage. The velcro closure makes them very easy to put on and take off, and to adjust to your size.",
        price: 150,
        type: 'accesorie',
        stock: 12,
    },
    
];

export default myProducts;